#!/usr/bin/env python3
"""
Generate web_files_embedded.gd from web-player directory
This script converts all HTML, CSS, and JS files into a GDScript constant dictionary
"""

import os
import json
from pathlib import Path

def escape_gdscript_string(content):
    """Escape a string for use in GDScript"""
    # Replace backslash first to avoid double-escaping
    content = content.replace('\\', '\\\\')
    # Replace quotes
    content = content.replace('"', '\\"')
    # Replace newlines
    content = content.replace('\n', '\\n')
    # Replace tabs
    content = content.replace('\t', '\\t')
    return content

def get_content_type(filepath):
    """Get MIME type for file"""
    ext = filepath.suffix.lower()
    types = {
        '.html': 'text/html',
        '.css': 'text/css',
        '.js': 'application/javascript',
        '.json': 'application/json',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.gif': 'image/gif',
        '.svg': 'image/svg+xml',
    }
    return types.get(ext, 'application/octet-stream')

def main():
    project_root = Path(__file__).parent
    web_player_dir = project_root / 'web-player'
    output_file = project_root / 'scripts' / 'autoload' / 'web_files_embedded.gd'

    if not web_player_dir.exists():
        print(f"Error: web-player directory not found at {web_player_dir}")
        return 1

    print(f"Scanning {web_player_dir} for web files...")

    # Collect all files
    files_data = {}

    # Walk the web-player directory
    for filepath in web_player_dir.rglob('*'):
        if filepath.is_file():
            # Get relative path from web-player directory
            rel_path = filepath.relative_to(web_player_dir)

            # Convert to web path (forward slashes, leading slash)
            web_path = '/' + str(rel_path).replace('\\', '/')

            # Special case: index.html should also be accessible at /
            if rel_path.name == 'index.html' and rel_path.parent == Path('.'):
                web_path = '/'

            # Read file content
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                    escaped_content = escape_gdscript_string(content)
                    files_data[web_path] = escaped_content
                    print(f"  Added: {web_path} ({len(content)} bytes)")

                    # If this is index.html, also add it with its normal path
                    if rel_path.name == 'index.html' and rel_path.parent == Path('.'):
                        normal_path = '/index.html'
                        files_data[normal_path] = escaped_content
                        print(f"  Added: {normal_path} (alias)")

            except Exception as e:
                print(f"  Warning: Could not read {filepath}: {e}")

    if not files_data:
        print("Error: No files found to embed")
        return 1

    # Generate GDScript file
    print(f"\nGenerating {output_file}...")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('# Auto-generated file - DO NOT EDIT MANUALLY\n')
        f.write('# Generated by generate_web_files.py\n')
        f.write('# Contains embedded web player files as GDScript constants\n\n')
        f.write('extends Node\n\n')
        f.write('# Dictionary mapping web paths to file contents\n')
        f.write('const WEB_FILES = {\n')

        for path, content in sorted(files_data.items()):
            f.write(f'\t"{path}": "{content}",\n')

        f.write('}\n')

    print(f"✓ Generated {output_file}")
    print(f"✓ Embedded {len(files_data)} files")

    return 0

if __name__ == '__main__':
    exit(main())
